//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformsMVCAsyncExampleNetStandard.ServicioPrueba {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Transaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CuentaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CuentaOrigen {
            get {
                return this.CuentaOrigenField;
            }
            set {
                if ((this.CuentaOrigenField.Equals(value) != true)) {
                    this.CuentaOrigenField = value;
                    this.RaisePropertyChanged("CuentaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion {
            get {
                return this.TipoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTransaccionField, value) != true)) {
                    this.TipoTransaccionField = value;
                    this.RaisePropertyChanged("TipoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titular {
            get {
                return this.TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularField, value) != true)) {
                    this.TitularField = value;
                    this.RaisePropertyChanged("Titular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorTransaccion {
            get {
                return this.ValorTransaccionField;
            }
            set {
                if ((this.ValorTransaccionField.Equals(value) != true)) {
                    this.ValorTransaccionField = value;
                    this.RaisePropertyChanged("ValorTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saldo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Saldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CuentaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SaldoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CuentaOrigen {
            get {
                return this.CuentaOrigenField;
            }
            set {
                if ((this.CuentaOrigenField.Equals(value) != true)) {
                    this.CuentaOrigenField = value;
                    this.RaisePropertyChanged("CuentaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SaldoCuenta {
            get {
                return this.SaldoCuentaField;
            }
            set {
                if ((this.SaldoCuentaField.Equals(value) != true)) {
                    this.SaldoCuentaField = value;
                    this.RaisePropertyChanged("SaldoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titular {
            get {
                return this.TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularField, value) != true)) {
                    this.TitularField = value;
                    this.RaisePropertyChanged("Titular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPrueba.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Transaccion[] GetData(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Transaccion[]> GetDataAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveData", ReplyAction="http://tempuri.org/IService/SaveDataResponse")]
        void SaveData(string usuario, string password, WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Saldo[] Saldos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveData", ReplyAction="http://tempuri.org/IService/SaveDataResponse")]
        System.Threading.Tasks.Task SaveDataAsync(string usuario, string password, WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Saldo[] Saldos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClaveCifradoCuenta", ReplyAction="http://tempuri.org/IService/GetClaveCifradoCuentaResponse")]
        string GetClaveCifradoCuenta(string usuario, string password, long CuentaOrigen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClaveCifradoCuenta", ReplyAction="http://tempuri.org/IService/GetClaveCifradoCuentaResponse")]
        System.Threading.Tasks.Task<string> GetClaveCifradoCuentaAsync(string usuario, string password, long CuentaOrigen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WinformsMVCAsyncExampleNetStandard.ServicioPrueba.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WinformsMVCAsyncExampleNetStandard.ServicioPrueba.IService>, WinformsMVCAsyncExampleNetStandard.ServicioPrueba.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Transaccion[] GetData(string usuario, string password) {
            return base.Channel.GetData(usuario, password);
        }
        
        public System.Threading.Tasks.Task<WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Transaccion[]> GetDataAsync(string usuario, string password) {
            return base.Channel.GetDataAsync(usuario, password);
        }
        
        public void SaveData(string usuario, string password, WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Saldo[] Saldos) {
            base.Channel.SaveData(usuario, password, Saldos);
        }
        
        public System.Threading.Tasks.Task SaveDataAsync(string usuario, string password, WinformsMVCAsyncExampleNetStandard.ServicioPrueba.Saldo[] Saldos) {
            return base.Channel.SaveDataAsync(usuario, password, Saldos);
        }
        
        public string GetClaveCifradoCuenta(string usuario, string password, long CuentaOrigen) {
            return base.Channel.GetClaveCifradoCuenta(usuario, password, CuentaOrigen);
        }
        
        public System.Threading.Tasks.Task<string> GetClaveCifradoCuentaAsync(string usuario, string password, long CuentaOrigen) {
            return base.Channel.GetClaveCifradoCuentaAsync(usuario, password, CuentaOrigen);
        }
    }
}
